"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useRouter,useSearchParams} from "next/navigation";
import Link from "next/link";

function ReturnsPageContent(){
 const s=createClient(),router=useRouter(),params=useSearchParams();
 const [view,setView]=useState(params.get("view")==="history"?"history":"returns");
 const [type,setType]=useState<"sale"|"purchase">("sale"),[docs,setDocs]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[items,setItems]=useState<any[]>([]),[msg,setMsg]=useState(""),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(false);
 async function loadDocs(){const table=type==="sale"?"sales":"purchases";const date=type==="sale"?"sale_date":"purchase_date";const r=await s.from(table).select("id,invoice_no,warehouse_id,grand_total,created_at,warehouses(name)").eq("status","posted").order(date,{ascending:false}).limit(100);if(r.error)setMsg(r.error.message);setDocs(r.data??[])}
 async function loadHistory(){const [a,b,c,d]=await Promise.all([s.from("sales").select("id,invoice_no,sale_date,status,grand_total").order("sale_date",{ascending:false}).limit(100),s.from("purchases").select("id,invoice_no,purchase_date,status,grand_total").order("purchase_date",{ascending:false}).limit(100),s.from("sale_returns").select("id,return_no,return_date,status,total_amount").order("return_date",{ascending:false}).limit(100),s.from("purchase_returns").select("id,return_no,return_date,status,total_amount").order("return_date",{ascending:false}).limit(100)]);const rows=[...(a.data??[]).map(x=>({...x,type:"Penjualan",no:x.invoice_no,date:x.sale_date,amount:x.grand_total})),...(b.data??[]).map(x=>({...x,type:"Pembelian",no:x.invoice_no,date:x.purchase_date,amount:x.grand_total})),...(c.data??[]).map(x=>({...x,type:"Retur Penjualan",no:x.return_no,date:x.return_date,amount:x.total_amount})),...(d.data??[]).map(x=>({...x,type:"Retur Pembelian",no:x.return_no,date:x.return_date,amount:x.total_amount}))].sort((x,y)=>new Date(y.date).getTime()-new Date(x.date).getTime());setHistory(rows)}
 useEffect(()=>{s.auth.getUser().then(({data})=>{if(!data.user)router.replace("/login");else if(view==="returns")loadDocs();else loadHistory()})},[type,view]);
 async function openDoc(d:any){setSelected(d);const table=type==="sale"?"sale_items":"purchase_items",fk=type==="sale"?"sale_id":"purchase_id";const r=await s.from(table).select("id,product_id,quantity,unit_price,unit_cost,subtotal,products(name,sku)").eq(fk,d.id);setItems(r.data??[])}
 async function postReturn(){if(!selected||!items.length)return;setLoading(true);const header=type==="sale"?"sale_returns":"purchase_returns",detail=type==="sale"?"sale_return_items":"purchase_return_items",fk=type==="sale"?"sale_id":"purchase_id";const u=await s.auth.getUser();const p:any={return_no:(type==="sale"?"SR-":"PR-")+Date.now(),[fk]:selected.id,warehouse_id:selected.warehouse_id,reason:"Retur dari riwayat transaksi",created_by:u.data.user?.id};const h=await s.from(header).insert(p).select("id").single();if(h.error){setMsg(h.error.message);setLoading(false);return}const rows=items.map(x=>({[type==="sale"?"sale_return_id":"purchase_return_id"]:h.data.id,product_id:x.product_id,quantity:Number(x.quantity),...(type==="sale"?{unit_price:Number(x.unit_price)}:{unit_cost:Number(x.unit_cost)})}));const d=await s.from(detail).insert(rows);if(d.error){setMsg(d.error.message);setLoading(false);return}const r=await s.rpc(type==="sale"?"post_sale_return":"post_purchase_return",{p_return_id:h.data.id});setLoading(false);setMsg(r.error?r.error.message:"Retur berhasil diposting dan stok diperbarui.");if(!r.error){setSelected(null);loadDocs()}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">PB</div><div><strong>Pecah Belah</strong><span>ERP System</span></div></div><div className="workspace"><span className="dot"/> Transaksi</div><nav className="nav"><Link href="/dashboard">Dashboard</Link><Link href="/pos">Kasir / POS</Link><Link href="/products">Produk & Stok</Link><Link href="/purchases">Pembelian</Link><Link href="/returns" className={view==="returns"?"active":""}>Retur</Link><Link href="/returns?view=history" className={view==="history"?"active":""}>Riwayat Transaksi</Link><Link href="/reports">Laporan</Link></nav></aside>
 <main className="main"><div className="topbar"><div><h1>{view==="returns"?"Retur":"Riwayat Transaksi"}</h1><span className="muted">{view==="returns"?"Kembalikan barang dari transaksi yang sudah posted":"Semua transaksi penjualan, pembelian, dan retur"}</span></div></div>
 <div className="tabs"><button className={view==="returns"?"btn btn-primary":"btn btn-light"} onClick={()=>setView("returns")}>Retur</button><button className={view==="history"?"btn btn-primary":"btn btn-light"} onClick={()=>setView("history")}>Riwayat Transaksi</button></div>
 {msg&&<p className={msg.includes("berhasil")?"success":"danger"}>{msg}</p>}
 {view==="history"?<div className="table-wrap"><table className="table"><thead><tr><th>Nomor</th><th>Jenis</th><th>Tanggal</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{history.map(x=><tr key={x.type+x.id}><td>{x.no}</td><td>{x.type}</td><td>{new Date(x.date).toLocaleString("id-ID")}</td><td>{x.status}</td><td>Rp {Number(x.amount||0).toLocaleString("id-ID")}</td><td>{(x.type==="Penjualan"||x.type==="Pembelian")&&<Link className="btn btn-light" href={`/transactions/detail?id=${x.id}&type=${x.type==="Penjualan"?"sale":"purchase"}`}>Detail / Cetak</Link>}</td></tr>)}{!history.length&&<tr><td colSpan={6}>Belum ada transaksi.</td></tr>}</tbody></table></div>:<><div className="tabs"><button className={type==="sale"?"btn btn-primary":"btn btn-light"} onClick={()=>{setType("sale");setSelected(null)}}>Retur Penjualan</button><button className={type==="purchase"?"btn btn-primary":"btn btn-light"} onClick={()=>{setType("purchase");setSelected(null)}}>Retur Pembelian</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Tanggal</th><th>Gudang</th><th>Total</th><th></th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.invoice_no}</td><td>{new Date(d.created_at).toLocaleString("id-ID")}</td><td>{d.warehouses?.name||"-"}</td><td>Rp {Number(d.grand_total).toLocaleString("id-ID")}</td><td><button className="btn btn-light" onClick={()=>openDoc(d)}>Pilih</button></td></tr>)}{!docs.length&&<tr><td colSpan={5}>Belum ada transaksi posted.</td></tr>}</tbody></table></div></>}
 {selected&&<div className="modal"><div className="modal-card"><div className="section-head"><h2>Konfirmasi Retur {selected.invoice_no}</h2><button className="btn btn-light" onClick={()=>setSelected(null)}>Tutup</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Produk</th><th>Qty</th><th>Harga</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.products?.name}<div className="muted">{x.products?.sku}</div></td><td>{x.quantity}</td><td>Rp {Number(type==="sale"?x.unit_price:x.unit_cost).toLocaleString("id-ID")}</td></tr>)}</tbody></table></div><button className="btn btn-primary" disabled={loading} onClick={postReturn}>{loading?"Memproses...":"Posting Retur & Perbarui Stok"}</button></div></div>}
 </main><nav className="mobile-nav"><Link href="/dashboard">Dashboard</Link><Link href="/pos">POS</Link><Link href="/returns">Retur</Link><Link href="/returns?view=history">Riwayat</Link></nav></div>
}
export default function ReturnsPage(){return <Suspense fallback={<main className="main"><p>Memuat...</p></main>}><ReturnsPageContent/></Suspense>}
