"use client";
import {Suspense,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useRouter,useSearchParams} from "next/navigation";
import Link from "next/link";
function TransactionDetailPageContent(){
 const s=createClient(),router=useRouter(),params=useSearchParams(); const id=params.get("id"),type=params.get("type")||"sale"; const [doc,setDoc]=useState<any>(null),[items,setItems]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{s.auth.getUser().then(async({data})=>{if(!data.user){router.replace("/login");return} if(!id){setLoading(false);return} const table=type==="purchase"?"purchases":"sales",fk=type==="purchase"?"purchase_id":"sale_id",itemTable=type==="purchase"?"purchase_items":"sale_items"; const [d,i,p]=await Promise.all([s.from(table).select("*,warehouses(name),customers(name),suppliers(name)").eq("id",id).single(),s.from(itemTable).select("*,products(name,sku)").eq(fk,id),s.from("payments").select("*").eq(fk,id).order("payment_date")]); setDoc(d.data);setItems(i.data??[]);setPayments(p.data??[]);setLoading(false)})},[id,type]);
 if(loading)return <main className="main"><p>Memuat transaksi...</p></main>; if(!doc)return <main className="main"><p className="danger">Transaksi tidak ditemukan.</p></main>; const purchase=type==="purchase";
 return <div className="receipt"><div className="receipt-paper"><div className="no-print" style={{textAlign:"left",marginBottom:16}}><Link href="/returns?view=history" className="btn btn-light">← Kembali</Link></div><h2 style={{marginBottom:4}}>PECAH BELAH</h2><div>ERP Toko</div><hr/><h3>{purchase?"NOTA PEMBELIAN":"NOTA PENJUALAN"}</h3><div>{doc.invoice_no}</div><div className="receipt-line"><span>Tanggal</span><span>{new Date(doc.sale_date||doc.purchase_date).toLocaleString("id-ID")}</span></div><div className="receipt-line"><span>Gudang</span><span>{doc.warehouses?.name||"-"}</span></div><div className="receipt-line"><span>{purchase?"Supplier":"Customer"}</span><span>{doc.suppliers?.name||doc.customers?.name||"Umum"}</span></div><hr/>{items.map(x=><div key={x.id} style={{textAlign:"left",margin:"10px 0"}}><strong>{x.products?.name}</strong><div className="receipt-line"><span>{x.quantity} × Rp {Number(purchase?x.unit_cost:x.unit_price).toLocaleString("id-ID")}</span><span>Rp {Number(x.subtotal).toLocaleString("id-ID")}</span></div></div>)}<hr/><div className="receipt-line"><strong>Subtotal</strong><strong>Rp {Number(doc.subtotal).toLocaleString("id-ID")}</strong></div><div className="receipt-line"><span>Diskon</span><span>Rp {Number(doc.discount||0).toLocaleString("id-ID")}</span></div><div className="receipt-line"><strong>Total</strong><strong>Rp {Number(doc.grand_total).toLocaleString("id-ID")}</strong></div>{!purchase&&payments.length>0&&<><hr/><strong>Pembayaran</strong>{payments.map(p=><div className="receipt-line" key={p.id}><span>{p.payment_method}</span><span>Rp {Number(p.amount).toLocaleString("id-ID")}</span></div>)}</>}<button className="btn btn-primary print-btn no-print" onClick={()=>window.print()}>Cetak / Simpan PDF</button></div></div>;
}
export default function TransactionDetailPage(){return <Suspense fallback={<main className="main"><p>Memuat transaksi...</p></main>}><TransactionDetailPageContent/></Suspense>}
